coverage:
  status:
    patch:
      default:
        informational: true # Shows the patch metric but never turns red/fails the PR

ignore:
  - "examples/**"
  - "**/stringers.go"
  - "**/*_stringers.go"
