// Code generated by "stringer -type=FieldClass -linecomment -output stringers.go ."; DO NOT EDIT.

package pcap

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[fieldClassUndefined-0]
	_ = x[FieldClassSrc-1]
	_ = x[FieldClassDst-2]
	_ = x[FieldClassProto-3]
	_ = x[FieldClassVersion-4]
	_ = x[FieldClassType-5]
	_ = x[FieldClassSize-6]
	_ = x[FieldClassFlags-7]
	_ = x[FieldClassID-8]
	_ = x[FieldClassChecksum-9]
	_ = x[FieldClassOptions-10]
	_ = x[FieldClassPayload-11]
	_ = x[FieldClassText-12]
	_ = x[FieldClassAddress-13]
	_ = x[FieldClassBinaryText-14]
	_ = x[FieldClassOperation-15]
	_ = x[FieldClassTimestamp-16]
}

const _FieldClass_name = "undefinedsourcedestinationprotocolversiontypesizeflagsidentificationchecksumoptionspayloadtextaddressbinary-textoptimestamp"

var _FieldClass_index = [...]uint8{0, 9, 15, 26, 34, 41, 45, 49, 54, 68, 76, 83, 90, 94, 101, 112, 114, 123}

func (i FieldClass) String() string {
	if i >= FieldClass(len(_FieldClass_index)-1) {
		return "FieldClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FieldClass_name[_FieldClass_index[i]:_FieldClass_index[i+1]]
}
