// Code generated by "stringer -type=Type,CodeDestinationUnreachable,CodeParameterProblem -linecomment -output stringers.go"; DO NOT EDIT.

package icmpv6

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeDestinationUnreachable-1]
	_ = x[TypePacketTooBig-2]
	_ = x[TypeTimeExceeded-3]
	_ = x[TypeParameterProblem-4]
	_ = x[TypeEchoRequest-128]
	_ = x[TypeEchoReply-129]
	_ = x[TypeRouterSolicitation-133]
	_ = x[TypeRouterAdvertisement-134]
	_ = x[TypeNeighborSolicitation-135]
	_ = x[TypeNeighborAdvertisement-136]
	_ = x[TypeRedirectMessage-137]
}

const (
	_Type_name_0 = "destination unreachablepacket too bigtime exceededparameter problem"
	_Type_name_1 = "echo requestecho reply"
	_Type_name_2 = "router solicitationrouter advertisementneighbor solicitationneighbor advertisementredirect message"
)

var (
	_Type_index_0 = [...]uint8{0, 23, 37, 50, 67}
	_Type_index_1 = [...]uint8{0, 12, 22}
	_Type_index_2 = [...]uint8{0, 19, 39, 60, 82, 98}
)

func (i Type) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _Type_name_0[_Type_index_0[i]:_Type_index_0[i+1]]
	case 128 <= i && i <= 129:
		i -= 128
		return _Type_name_1[_Type_index_1[i]:_Type_index_1[i+1]]
	case 133 <= i && i <= 137:
		i -= 133
		return _Type_name_2[_Type_index_2[i]:_Type_index_2[i+1]]
	default:
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeNoRoute-0]
	_ = x[CodeAdminProhibited-1]
	_ = x[CodeBeyondScope-2]
	_ = x[CodeAddressUnreachable-3]
	_ = x[CodePortUnreachable-4]
	_ = x[CodeIngressEgressPolicy-5]
	_ = x[CodeRejectRoute-6]
}

const _CodeDestinationUnreachable_name = "no route to destinationcommunication administratively prohibitedbeyond scope of source addressaddress unreachableport unreachablesource address failed ingress/egress policyreject route to destination"

var _CodeDestinationUnreachable_index = [...]uint8{0, 23, 64, 94, 113, 129, 172, 199}

func (i CodeDestinationUnreachable) String() string {
	if i >= CodeDestinationUnreachable(len(_CodeDestinationUnreachable_index)-1) {
		return "CodeDestinationUnreachable(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CodeDestinationUnreachable_name[_CodeDestinationUnreachable_index[i]:_CodeDestinationUnreachable_index[i+1]]
}

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeErroneousHeaderField-0]
	_ = x[CodeUnrecognizedNextHeader-1]
	_ = x[CodeUnrecognizedIPv6Option-2]
}

const _CodeParameterProblem_name = "erroneous header field encounteredunrecognized next header type encounteredunrecognized IPv6 option encountered"

var _CodeParameterProblem_index = [...]uint8{0, 34, 75, 111}

func (i CodeParameterProblem) String() string {
	if i >= CodeParameterProblem(len(_CodeParameterProblem_index)-1) {
		return "CodeParameterProblem(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CodeParameterProblem_name[_CodeParameterProblem_index[i]:_CodeParameterProblem_index[i+1]]
}
