// Code generated by "stringer -type Method -linecomment -output stringers.go"; DO NOT EDIT.

package httphi

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethUndefined-0]
	_ = x[MethGet-1]
	_ = x[MethHead-2]
	_ = x[MethPost-3]
	_ = x[MethPut-4]
	_ = x[MethPatch-5]
	_ = x[MethDelete-6]
	_ = x[MethConnect-7]
	_ = x[MethOptions-8]
	_ = x[MethTrace-9]
	_ = x[MethUnknown-10]
}

const _Method_name = "undefinedGETHEADPOSTPUTPATCHDELETECONNECTOPTIONSTRACEunknown"

var _Method_index = [...]uint8{0, 9, 12, 16, 20, 23, 28, 34, 41, 48, 53, 60}

func (i Method) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Method_index)-1 {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[idx]:_Method_index[idx+1]]
}
