// Code generated by "stringer -type=MsgType,DisconnectReason,ChannelOpenFailureReason -linecomment -output stringers.go ."; DO NOT EDIT.

package sshraw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[_msgUndefined-0]
	_ = x[MsgDisconnect-1]
	_ = x[MsgIgnore-2]
	_ = x[MsgUnimplemented-3]
	_ = x[MsgDebug-4]
	_ = x[MsgServiceRequest-5]
	_ = x[MsgServiceAccept-6]
	_ = x[MsgExtInfo-7]
	_ = x[MsgKexInit-20]
	_ = x[MsgNewKeys-21]
	_ = x[MsgKexECDHInit-30]
	_ = x[MsgKexECDHReply-31]
	_ = x[MsgUserauthRequest-50]
	_ = x[MsgUserauthFailure-51]
	_ = x[MsgUserauthSuccess-52]
	_ = x[MsgUserauthBanner-53]
	_ = x[MsgUserauthPKOK-60]
	_ = x[MsgGlobalRequest-80]
	_ = x[MsgRequestSuccess-81]
	_ = x[MsgRequestFailure-82]
	_ = x[MsgChannelOpen-90]
	_ = x[MsgChannelOpenConfirmation-91]
	_ = x[MsgChannelOpenFailure-92]
	_ = x[MsgChannelWindowAdjust-93]
	_ = x[MsgChannelData-94]
	_ = x[MsgChannelExtendedData-95]
	_ = x[MsgChannelEOF-96]
	_ = x[MsgChannelClose-97]
	_ = x[MsgChannelRequest-98]
	_ = x[MsgChannelSuccess-99]
	_ = x[MsgChannelFailure-100]
}

const (
	_MsgType_name_0 = "undefinedDISCONNECTIGNOREUNIMPLEMENTEDDEBUGSERVICE_REQUESTSERVICE_ACCEPTEXT_INFO"
	_MsgType_name_1 = "KEXINITNEWKEYS"
	_MsgType_name_2 = "KEX_ECDH_INITKEX_ECDH_REPLY"
	_MsgType_name_3 = "USERAUTH_REQUESTUSERAUTH_FAILUREUSERAUTH_SUCCESSUSERAUTH_BANNER"
	_MsgType_name_4 = "USERAUTH_PK_OK"
	_MsgType_name_5 = "GLOBAL_REQUESTREQUEST_SUCCESSREQUEST_FAILURE"
	_MsgType_name_6 = "CHANNEL_OPENCHANNEL_OPEN_CONFIRMATIONCHANNEL_OPEN_FAILURECHANNEL_WINDOW_ADJUSTCHANNEL_DATACHANNEL_EXTENDED_DATACHANNEL_EOFCHANNEL_CLOSECHANNEL_REQUESTCHANNEL_SUCCESSCHANNEL_FAILURE"
)

var (
	_MsgType_index_0 = [...]uint8{0, 9, 19, 25, 38, 43, 58, 72, 80}
	_MsgType_index_1 = [...]uint8{0, 7, 14}
	_MsgType_index_2 = [...]uint8{0, 13, 27}
	_MsgType_index_3 = [...]uint8{0, 16, 32, 48, 63}
	_MsgType_index_5 = [...]uint8{0, 14, 29, 44}
	_MsgType_index_6 = [...]uint8{0, 12, 37, 57, 78, 90, 111, 122, 135, 150, 165, 180}
)

func (i MsgType) String() string {
	switch {
	case i <= 7:
		return _MsgType_name_0[_MsgType_index_0[i]:_MsgType_index_0[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _MsgType_name_1[_MsgType_index_1[i]:_MsgType_index_1[i+1]]
	case 30 <= i && i <= 31:
		i -= 30
		return _MsgType_name_2[_MsgType_index_2[i]:_MsgType_index_2[i+1]]
	case 50 <= i && i <= 53:
		i -= 50
		return _MsgType_name_3[_MsgType_index_3[i]:_MsgType_index_3[i+1]]
	case i == 60:
		return _MsgType_name_4
	case 80 <= i && i <= 82:
		i -= 80
		return _MsgType_name_5[_MsgType_index_5[i]:_MsgType_index_5[i+1]]
	case 90 <= i && i <= 100:
		i -= 90
		return _MsgType_name_6[_MsgType_index_6[i]:_MsgType_index_6[i+1]]
	default:
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DisconnectHostNotAllowedToConnect-1]
	_ = x[DisconnectProtocolError-2]
	_ = x[DisconnectKeyExchangeFailed-3]
	_ = x[DisconnectReserved-4]
	_ = x[DisconnectMACError-5]
	_ = x[DisconnectCompressionError-6]
	_ = x[DisconnectServiceNotAvailable-7]
	_ = x[DisconnectProtocolVersionNotSupported-8]
	_ = x[DisconnectHostKeyNotVerifiable-9]
	_ = x[DisconnectConnectionLost-10]
	_ = x[DisconnectByApplication-11]
	_ = x[DisconnectTooManyConnections-12]
	_ = x[DisconnectAuthCancelledByUser-13]
	_ = x[DisconnectNoMoreAuthMethodsAvailable-14]
	_ = x[DisconnectIllegalUserName-15]
}

const _DisconnectReason_name = "HOST_NOT_ALLOWED_TO_CONNECTPROTOCOL_ERRORKEY_EXCHANGE_FAILEDRESERVEDMAC_ERRORCOMPRESSION_ERRORSERVICE_NOT_AVAILABLEPROTOCOL_VERSION_NOT_SUPPORTEDHOST_KEY_NOT_VERIFIABLECONNECTION_LOSTBY_APPLICATIONTOO_MANY_CONNECTIONSAUTH_CANCELLED_BY_USERNO_MORE_AUTH_METHODS_AVAILABLEILLEGAL_USER_NAME"

var _DisconnectReason_index = [...]uint16{0, 27, 41, 60, 68, 77, 94, 115, 145, 168, 183, 197, 217, 239, 269, 286}

func (i DisconnectReason) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DisconnectReason_index)-1 {
		return "DisconnectReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DisconnectReason_name[_DisconnectReason_index[idx]:_DisconnectReason_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpenAdministrativelyProhibited-1]
	_ = x[OpenConnectFailed-2]
	_ = x[OpenUnknownChannelType-3]
	_ = x[OpenResourceShortage-4]
}

const _ChannelOpenFailureReason_name = "ADMINISTRATIVELY_PROHIBITEDCONNECT_FAILEDUNKNOWN_CHANNEL_TYPERESOURCE_SHORTAGE"

var _ChannelOpenFailureReason_index = [...]uint8{0, 27, 41, 61, 78}

func (i ChannelOpenFailureReason) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ChannelOpenFailureReason_index)-1 {
		return "ChannelOpenFailureReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelOpenFailureReason_name[_ChannelOpenFailureReason_index[idx]:_ChannelOpenFailureReason_index[idx+1]]
}
