// Code generated by "stringer -type=MsgType,DisconnectReason,ChannelOpenFailureReason -linecomment -output stringers.go ."; DO NOT EDIT.

package sshraw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgDisconnect-1]
	_ = x[MsgIgnore-2]
	_ = x[MsgUnimplemented-3]
	_ = x[MsgDebug-4]
	_ = x[MsgServiceRequest-5]
	_ = x[MsgServiceAccept-6]
	_ = x[MsgExtInfo-7]
	_ = x[MsgKexInit-20]
	_ = x[MsgNewKeys-21]
	_ = x[MsgKexECDHInit-30]
	_ = x[MsgKexECDHReply-31]
	_ = x[MsgUserauthRequest-50]
	_ = x[MsgUserauthFailure-51]
	_ = x[MsgUserauthSuccess-52]
	_ = x[MsgUserauthBanner-53]
	_ = x[MsgUserauthPKOK-60]
	_ = x[MsgGlobalRequest-80]
	_ = x[MsgRequestSuccess-81]
	_ = x[MsgRequestFailure-82]
	_ = x[MsgChannelOpen-90]
	_ = x[MsgChannelOpenConfirmation-91]
	_ = x[MsgChannelOpenFailure-92]
	_ = x[MsgChannelWindowAdjust-93]
	_ = x[MsgChannelData-94]
	_ = x[MsgChannelExtendedData-95]
	_ = x[MsgChannelEOF-96]
	_ = x[MsgChannelClose-97]
	_ = x[MsgChannelRequest-98]
	_ = x[MsgChannelSuccess-99]
	_ = x[MsgChannelFailure-100]
}

const (
	_MsgType_name_0 = "SSH_MSG_DISCONNECTSSH_MSG_IGNORESSH_MSG_UNIMPLEMENTEDSSH_MSG_DEBUGSSH_MSG_SERVICE_REQUESTSSH_MSG_SERVICE_ACCEPTSSH_MSG_EXT_INFO"
	_MsgType_name_1 = "SSH_MSG_KEXINITSSH_MSG_NEWKEYS"
	_MsgType_name_2 = "SSH_MSG_KEX_ECDH_INITSSH_MSG_KEX_ECDH_REPLY"
	_MsgType_name_3 = "SSH_MSG_USERAUTH_REQUESTSSH_MSG_USERAUTH_FAILURESSH_MSG_USERAUTH_SUCCESSSSH_MSG_USERAUTH_BANNER"
	_MsgType_name_4 = "SSH_MSG_USERAUTH_PK_OK"
	_MsgType_name_5 = "SSH_MSG_GLOBAL_REQUESTSSH_MSG_REQUEST_SUCCESSSSH_MSG_REQUEST_FAILURE"
	_MsgType_name_6 = "SSH_MSG_CHANNEL_OPENSSH_MSG_CHANNEL_OPEN_CONFIRMATIONSSH_MSG_CHANNEL_OPEN_FAILURESSH_MSG_CHANNEL_WINDOW_ADJUSTSSH_MSG_CHANNEL_DATASSH_MSG_CHANNEL_EXTENDED_DATASSH_MSG_CHANNEL_EOFSSH_MSG_CHANNEL_CLOSESSH_MSG_CHANNEL_REQUESTSSH_MSG_CHANNEL_SUCCESSSSH_MSG_CHANNEL_FAILURE"
)

var (
	_MsgType_index_0 = [...]uint8{0, 18, 32, 53, 66, 89, 111, 127}
	_MsgType_index_1 = [...]uint8{0, 15, 30}
	_MsgType_index_2 = [...]uint8{0, 21, 43}
	_MsgType_index_3 = [...]uint8{0, 24, 48, 72, 95}
	_MsgType_index_5 = [...]uint8{0, 22, 45, 68}
	_MsgType_index_6 = [...]uint16{0, 20, 53, 81, 110, 130, 159, 178, 199, 222, 245, 268}
)

func (i MsgType) String() string {
	switch {
	case 1 <= i && i <= 7:
		i -= 1
		return _MsgType_name_0[_MsgType_index_0[i]:_MsgType_index_0[i+1]]
	case 20 <= i && i <= 21:
		i -= 20
		return _MsgType_name_1[_MsgType_index_1[i]:_MsgType_index_1[i+1]]
	case 30 <= i && i <= 31:
		i -= 30
		return _MsgType_name_2[_MsgType_index_2[i]:_MsgType_index_2[i+1]]
	case 50 <= i && i <= 53:
		i -= 50
		return _MsgType_name_3[_MsgType_index_3[i]:_MsgType_index_3[i+1]]
	case i == 60:
		return _MsgType_name_4
	case 80 <= i && i <= 82:
		i -= 80
		return _MsgType_name_5[_MsgType_index_5[i]:_MsgType_index_5[i+1]]
	case 90 <= i && i <= 100:
		i -= 90
		return _MsgType_name_6[_MsgType_index_6[i]:_MsgType_index_6[i+1]]
	default:
		return "MsgType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DisconnectHostNotAllowedToConnect-1]
	_ = x[DisconnectProtocolError-2]
	_ = x[DisconnectKeyExchangeFailed-3]
	_ = x[DisconnectReserved-4]
	_ = x[DisconnectMACError-5]
	_ = x[DisconnectCompressionError-6]
	_ = x[DisconnectServiceNotAvailable-7]
	_ = x[DisconnectProtocolVersionNotSupported-8]
	_ = x[DisconnectHostKeyNotVerifiable-9]
	_ = x[DisconnectConnectionLost-10]
	_ = x[DisconnectByApplication-11]
	_ = x[DisconnectTooManyConnections-12]
	_ = x[DisconnectAuthCancelledByUser-13]
	_ = x[DisconnectNoMoreAuthMethodsAvailable-14]
	_ = x[DisconnectIllegalUserName-15]
}

const _DisconnectReason_name = "SSH_DISCONNECT_HOST_NOT_ALLOWED_TO_CONNECTSSH_DISCONNECT_PROTOCOL_ERRORSSH_DISCONNECT_KEY_EXCHANGE_FAILEDSSH_DISCONNECT_RESERVEDSSH_DISCONNECT_MAC_ERRORSSH_DISCONNECT_COMPRESSION_ERRORSSH_DISCONNECT_SERVICE_NOT_AVAILABLESSH_DISCONNECT_PROTOCOL_VERSION_NOT_SUPPORTEDSSH_DISCONNECT_HOST_KEY_NOT_VERIFIABLESSH_DISCONNECT_CONNECTION_LOSTSSH_DISCONNECT_BY_APPLICATIONSSH_DISCONNECT_TOO_MANY_CONNECTIONSSSH_DISCONNECT_AUTH_CANCELLED_BY_USERSSH_DISCONNECT_NO_MORE_AUTH_METHODS_AVAILABLESSH_DISCONNECT_ILLEGAL_USER_NAME"

var _DisconnectReason_index = [...]uint16{0, 42, 71, 105, 128, 152, 184, 220, 265, 303, 333, 362, 397, 434, 479, 511}

func (i DisconnectReason) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_DisconnectReason_index)-1 {
		return "DisconnectReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DisconnectReason_name[_DisconnectReason_index[idx]:_DisconnectReason_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpenAdministrativelyProhibited-1]
	_ = x[OpenConnectFailed-2]
	_ = x[OpenUnknownChannelType-3]
	_ = x[OpenResourceShortage-4]
}

const _ChannelOpenFailureReason_name = "SSH_OPEN_ADMINISTRATIVELY_PROHIBITEDSSH_OPEN_CONNECT_FAILEDSSH_OPEN_UNKNOWN_CHANNEL_TYPESSH_OPEN_RESOURCE_SHORTAGE"

var _ChannelOpenFailureReason_index = [...]uint8{0, 36, 59, 88, 114}

func (i ChannelOpenFailureReason) String() string {
	idx := int(i) - 1
	if i < 1 || idx >= len(_ChannelOpenFailureReason_index)-1 {
		return "ChannelOpenFailureReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ChannelOpenFailureReason_name[_ChannelOpenFailureReason_index[idx]:_ChannelOpenFailureReason_index[idx+1]]
}
