// Code generated by "stringer -type=KERecordType,AEADAlgorithmID -linecomment -output stringers.go"; DO NOT EDIT.

package nts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RecordEndOfMessage-0]
	_ = x[RecordNextProtoNeg-1]
	_ = x[RecordError-2]
	_ = x[RecordWarning-3]
	_ = x[RecordAEADAlgNeg-4]
	_ = x[RecordNewCookie-5]
	_ = x[RecordNTPv4Server-6]
	_ = x[RecordNTPv4Port-7]
}

const _KERecordType_name = "end of messagenext protocol negotiationerrorwarningAEAD algorithm negotiationnew cookie for NTPv4NTPv4 server negotiationNTPv4 port negotiation"

var _KERecordType_index = [...]uint8{0, 14, 39, 44, 51, 77, 97, 121, 143}

func (i KERecordType) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_KERecordType_index)-1 {
		return "KERecordType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _KERecordType_name[_KERecordType_index[idx]:_KERecordType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlgAESSIVCMAC256-15]
}

const _AEADAlgorithmID_name = "AEAD_AES_SIV_CMAC_256"

var _AEADAlgorithmID_index = [...]uint8{0, 21}

func (i AEADAlgorithmID) String() string {
	idx := int(i) - 15
	if i < 15 || idx >= len(_AEADAlgorithmID_index)-1 {
		return "AEADAlgorithmID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AEADAlgorithmID_name[_AEADAlgorithmID_index[idx]:_AEADAlgorithmID_index[idx+1]]
}
