// Code generated by "stringer -type=ContentType,HandshakeType,AlertLevel,NamedGroup,SignatureScheme,CipherSuite -linecomment -output stringers.go ."; DO NOT EDIT.

package tlsraw

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentTypeInvalid-0]
	_ = x[ContentTypeChangeCipherSpec-20]
	_ = x[ContentTypeAlert-21]
	_ = x[ContentTypeHandshake-22]
	_ = x[ContentTypeApplicationData-23]
}

const (
	_ContentType_name_0 = "invalid"
	_ContentType_name_1 = "change_cipher_specalerthandshakeapplication_data"
)

var (
	_ContentType_index_1 = [...]uint8{0, 18, 23, 32, 48}
)

func (i ContentType) String() string {
	switch {
	case i == 0:
		return _ContentType_name_0
	case 20 <= i && i <= 23:
		i -= 20
		return _ContentType_name_1[_ContentType_index_1[i]:_ContentType_index_1[i+1]]
	default:
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HandshakeTypeClientHello-1]
	_ = x[HandshakeTypeServerHello-2]
	_ = x[HandshakeTypeNewSessionTicket-4]
	_ = x[HandshakeTypeEndOfEarlyData-5]
	_ = x[HandshakeTypeEncryptedExtensions-8]
	_ = x[HandshakeTypeCertificate-11]
	_ = x[HandshakeTypeCertificateRequest-13]
	_ = x[HandshakeTypeCertificateVerify-15]
	_ = x[HandshakeTypeFinished-20]
	_ = x[HandshakeTypeKeyUpdate-24]
	_ = x[HandshakeTypeMessageHash-254]
}

const (
	_HandshakeType_name_0 = "client_helloserver_hello"
	_HandshakeType_name_1 = "new_session_ticketend_of_early_data"
	_HandshakeType_name_2 = "encrypted_extensions"
	_HandshakeType_name_3 = "certificate"
	_HandshakeType_name_4 = "certificate_request"
	_HandshakeType_name_5 = "certificate_verify"
	_HandshakeType_name_6 = "finished"
	_HandshakeType_name_7 = "key_update"
	_HandshakeType_name_8 = "message_hash"
)

var (
	_HandshakeType_index_0 = [...]uint8{0, 12, 24}
	_HandshakeType_index_1 = [...]uint8{0, 18, 35}
)

func (i HandshakeType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _HandshakeType_name_0[_HandshakeType_index_0[i]:_HandshakeType_index_0[i+1]]
	case 4 <= i && i <= 5:
		i -= 4
		return _HandshakeType_name_1[_HandshakeType_index_1[i]:_HandshakeType_index_1[i+1]]
	case i == 8:
		return _HandshakeType_name_2
	case i == 11:
		return _HandshakeType_name_3
	case i == 13:
		return _HandshakeType_name_4
	case i == 15:
		return _HandshakeType_name_5
	case i == 20:
		return _HandshakeType_name_6
	case i == 24:
		return _HandshakeType_name_7
	case i == 254:
		return _HandshakeType_name_8
	default:
		return "HandshakeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertLevelWarning-1]
	_ = x[AlertLevelFatal-2]
}

const _AlertLevel_name = "warningfatal"

var _AlertLevel_index = [...]uint8{0, 7, 12}

func (i AlertLevel) String() string {
	i -= 1
	if i >= AlertLevel(len(_AlertLevel_index)-1) {
		return "AlertLevel(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _AlertLevel_name[_AlertLevel_index[i]:_AlertLevel_index[i+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GroupSECP256R1-23]
	_ = x[GroupSECP384R1-24]
	_ = x[GroupSECP521R1-25]
	_ = x[GroupX25519-29]
	_ = x[GroupX448-30]
	_ = x[GroupMLKEM512-512]
	_ = x[GroupMLKEM768-513]
	_ = x[GroupMLKEM1024-514]
	_ = x[GroupSECP256R1MLKEM768-4587]
	_ = x[GroupX25519MLKEM768-4588]
	_ = x[GroupSECP384R1MLKEM1024-4589]
}

const (
	_NamedGroup_name_0 = "secp256r1secp384r1secp521r1"
	_NamedGroup_name_1 = "x25519x448"
	_NamedGroup_name_2 = "MLKEM512MLKEM768MLKEM1024"
	_NamedGroup_name_3 = "SecP256r1MLKEM768X25519MLKEM768SecP384r1MLKEM1024"
)

var (
	_NamedGroup_index_0 = [...]uint8{0, 9, 18, 27}
	_NamedGroup_index_1 = [...]uint8{0, 6, 10}
	_NamedGroup_index_2 = [...]uint8{0, 8, 16, 25}
	_NamedGroup_index_3 = [...]uint8{0, 17, 31, 49}
)

func (i NamedGroup) String() string {
	switch {
	case 23 <= i && i <= 25:
		i -= 23
		return _NamedGroup_name_0[_NamedGroup_index_0[i]:_NamedGroup_index_0[i+1]]
	case 29 <= i && i <= 30:
		i -= 29
		return _NamedGroup_name_1[_NamedGroup_index_1[i]:_NamedGroup_index_1[i+1]]
	case 512 <= i && i <= 514:
		i -= 512
		return _NamedGroup_name_2[_NamedGroup_index_2[i]:_NamedGroup_index_2[i+1]]
	case 4587 <= i && i <= 4589:
		i -= 4587
		return _NamedGroup_name_3[_NamedGroup_index_3[i]:_NamedGroup_index_3[i+1]]
	default:
		return "NamedGroup(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SigRSAPKCS1SHA256-1025]
	_ = x[SigRSAPKCS1SHA384-1281]
	_ = x[SigRSAPKCS1SHA512-1537]
	_ = x[SigECDSAP256SHA256-1027]
	_ = x[SigECDSAP384SHA384-1283]
	_ = x[SigECDSAP521SHA512-1539]
	_ = x[SigRSAPSSRSAESHA256-2052]
	_ = x[SigRSAPSSRSAESHA384-2053]
	_ = x[SigRSAPSSRSAESHA512-2054]
	_ = x[SigEd25519-2055]
	_ = x[SigRSAPSSPSSSHA256-2057]
}

const (
	_SignatureScheme_name_0 = "rsa_pkcs1_sha256"
	_SignatureScheme_name_1 = "ecdsa_secp256r1_sha256"
	_SignatureScheme_name_2 = "rsa_pkcs1_sha384"
	_SignatureScheme_name_3 = "ecdsa_secp384r1_sha384"
	_SignatureScheme_name_4 = "rsa_pkcs1_sha512"
	_SignatureScheme_name_5 = "ecdsa_secp521r1_sha512"
	_SignatureScheme_name_6 = "rsa_pss_rsae_sha256rsa_pss_rsae_sha384rsa_pss_rsae_sha512ed25519"
	_SignatureScheme_name_7 = "rsa_pss_pss_sha256"
)

var (
	_SignatureScheme_index_6 = [...]uint8{0, 19, 38, 57, 64}
)

func (i SignatureScheme) String() string {
	switch {
	case i == 1025:
		return _SignatureScheme_name_0
	case i == 1027:
		return _SignatureScheme_name_1
	case i == 1281:
		return _SignatureScheme_name_2
	case i == 1283:
		return _SignatureScheme_name_3
	case i == 1537:
		return _SignatureScheme_name_4
	case i == 1539:
		return _SignatureScheme_name_5
	case 2052 <= i && i <= 2055:
		i -= 2052
		return _SignatureScheme_name_6[_SignatureScheme_index_6[i]:_SignatureScheme_index_6[i+1]]
	case i == 2057:
		return _SignatureScheme_name_7
	default:
		return "SignatureScheme(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SuiteAES128GCMSHA256-4865]
	_ = x[SuiteAES256GCMSHA384-4866]
	_ = x[SuiteChaCha20Poly1305SHA256-4867]
	_ = x[SuiteAES128CCMSHA256-4868]
	_ = x[SuiteAES128CCM8SHA256-4869]
}

const _CipherSuite_name = "TLS_AES_128_GCM_SHA256TLS_AES_256_GCM_SHA384TLS_CHACHA20_POLY1305_SHA256TLS_AES_128_CCM_SHA256TLS_AES_128_CCM_8_SHA256"

var _CipherSuite_index = [...]uint8{0, 22, 44, 72, 94, 118}

func (i CipherSuite) String() string {
	i -= 4865
	if i >= CipherSuite(len(_CipherSuite_index)-1) {
		return "CipherSuite(" + strconv.FormatInt(int64(i+4865), 10) + ")"
	}
	return _CipherSuite_name[_CipherSuite_index[i]:_CipherSuite_index[i+1]]
}
